PERIOD_TYPES = ['this_week', 'next_week', 'quarter']
PERIOD_PAIRS = [(a, b) for a in PERIOD_TYPES for b in PERIOD_TYPES if a != b]
POSITION_SYNC_SLEEP_IN_SECOND = 2

MOVING_AVERAGE_TIME_WINDOW_IN_SECOND = 60 * 10  # 10 minutes
SPREAD_DEVIATION_THRESHOLD = -26
