MOVING_AVERAGE_TIME_WINDOW_IN_SECOND = 60 * 10  # 10 minutes
SPREAD_DEVIATION_THRESHOLD = -26

# Trader
MIN_TIME_WINDOW_IN_SECOND = 10
SLOW_LEG_ORDER_FULFILLMENT_TIMEOUT_SECOND = 15
FAST_LEG_ORDER_FULFILLMENT_TIMEOUT_SECOND = 20

LONG = 'LONG'
SHORT = 'SHORT'