POSITION_SYNC_SLEEP_IN_SECOND = 2
ORDER_CANCELLER_SLEEP_IN_SECOND = 2
PENDING_ORDER_TTL_IN_SECOND = 1
MOVING_AVERAGE_TIME_WINDOW_IN_SECOND = 60 * 10  # 10 minutes
SPREAD_DEVIATION_THRESHOLD = -26

# Trader
MIN_TIME_WINDOW_IN_SECOND = 10
